### ISSUE TITLE
Workflow keeps saying 'Bad API'

### ISSUE THREAD

**Issue by mattiacolombomc** [earthpyy/alfred-pastebin#1]
As title. I'm sure that the API is right. I tried to put it into the Alfred variable both in 'API' and API formats, none of them worked. Thanks in advance for your help!

**Comment by earthpyy** [comment]
Hello, sorry for the late reply. Did you already get the `api_user_key` from Pastebin?

As you can see in the note:

> NOTE:
> All paste will be created under guest account.
> 
> If you want to create under your Pastebin account, please retrieve your 'api_user_key' and put it into environment variable named 'USER_KEY' on the right. See: https://pastebin.com/api#8

**Comment by mattiacolombomc** [comment]
Yes, obv! But it doesn’t work :(
Il 16 gen 2021, 14:47 +0100, Preeti Yuankrathok <notifications@github.com>, ha scritto:

**Comment by earthpyy** [comment]
@mattiacolombomc Hey, I already updated the workflow to v2.0.0, please check it out, re-config the workflow, and keep me updated whether it is working or not. Thanks!

**Comment by mattiacolombomc** [comment]
It works like charm! Thank you so much for your great work. Can I offer you a cup of coffee?
Il 16 gen 2021, 19:10 +0100, Preeti Yuankrathok <notifications@github.com>, ha scritto:

**Comment by earthpyy** [comment]
Cool! I'm glad you like it. You're very welcome! Here's my PayPal, https://paypal.me/earthpyy. Thanks and have a nice day! 😄

**Comment by earthpyy** [comment]
I'm closing this issue 😄
